name: watershed
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.13
  - numpy
  - xarray
  - netcdf4
  - matplotlib
  - earthaccess
  - requests
  - geopandas
  - rioxarray
  - shapely
  - earthaccess[virtualizarr]
  - pydap
  - rasterstats